name: Exosphere users service
description: Manages user accounts in Exosphere applications

setup: npm install
startup:
  command: node_modules/.bin/exo-js
  online-text: online at port


messages:
  receives:
    - users.create
    - users.list
    - user.get-details
    - user.update
  sends:
    - users.created
    - users.listed
    - user.details
    - user.not-found
    - user.updated
