name: Exosphere users service
description: Manages user accounts in Exosphere applications

setup: npm install
startup:
  command: node_modules/.bin/exo-js run --name {{name}} --exorelay-port {{exorelay-port}} --exocomm-port {{exocomm-port}}
  online-text: online at port


messages:
  receives:
    - users.create
    - users.list
  sends:
    - users.created
    - users.listed
